"""Add admin's columns 2

Revision ID: 183c8b8fff74
Revises: 9ea36dde317f
Create Date: 2026-02-09 20:20:37.483247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183c8b8fff74'
down_revision: Union[str, Sequence[str], None] = '9ea36dde317f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
