"""Add admin's columns

Revision ID: 9ea36dde317f
Revises: 36c4999f589e
Create Date: 2026-02-09 19:58:39.592672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea36dde317f'
down_revision: Union[str, Sequence[str], None] = '36c4999f589e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'admin_id')
    # ### end Alembic commands ###
